sudo: required
services:
  - docker

before_install:
  - docker build  -t eddie/react-docker  -f Dockerfile.dev .

script:
  - docker run -e CI=true eddie/react-docker npm run test
# instances region and names
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "monday"
  env: "Monday-env"
  bucket_name: "elasticbeanstalk-us-east-1-781604726393"
  bucket_path: "monday"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$SECRET_ACCESS_KEY"
  